Turn Dev. Quickstart to Migration Guide & Update Frontend with options to try & build.
obscuronet/obscuro-documentation pull request #14
Opened 2023-10-24 10:03 UTC by 0xjba

2023-10-24 10:04 UTC, 0xjba commented
I'll include the Try Obscuro with a guide on playing guessing game with few more details

2023-10-24 13:25 UTC, tudor-malene requested changes
the gist is to move the generic stuff to a separate doc.
Let's only keep the obscuro specific commands in this doc

2023-10-24 13:25 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +
Let's add a small paragraph here giving a high level overview of the steps.
(basically the stuff I wrote in discord)

2023-10-24 13:25 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +### Prerequisites
I don't think we need the detailed instructions on how  in this doc. 
 Let's move them to a different doc, and link to them.

2023-10-24 13:25 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +```bash
we need this step in this doc

2023-10-24 13:25 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +### 5. Configuring `hardhat.config.js`
we need this section as well.

2023-10-24 13:25 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +### 6. Running Your Project
this is standard stuff, so let's move to the separate doc

2023-10-24 13:25 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +Creating a user-friendly frontend is crucial for interacting with your smart contracts on Obscuro. This section will guide you through setting up a frontend application, installing necessary packages
let's move the generic stuff to a separate doc.

2023-10-24 13:25 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +Install the Obscuro Gateway Widget package to easily integrate the Obscuro network into your dApp:
let's keep just this section

2023-10-24 13:25 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +In case you are unable to install the Obscuro Gateway Widget package, you can use the Obscuro Gateway Library through CDN. Add the following script tag to your HTML file:
when would the user be unable to install? 
Let's move this to a troubleshooting page

2023-10-24 13:25 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +## 3.5. Running Your Application
this is generic

2023-10-30 18:46 UTC, 0xjba commented
Made all changes requested.

2023-10-31 13:55 UTC, tudor-malene reviewed
almost there

2023-10-31 13:55 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +
Let's use this:
>>

Migrating to Obscuro is a straight-forward process that immediately unlocks private state. 
There are three main types of changes you need to make:

1. Change your hardhat deployment script so that you can use `--network obscuro`
2. Add logic to your view functions to protect data (if needed).
3. Add a widget to your javascript UI to onboard Obscuro users.

2023-10-31 13:55 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +To begin building on Obscuro, start by setting up a Hardhat project as usual.
Let's  make it:
"##  1. Configure hardhat"

2023-10-31 13:55 UTC, tudor-malene commented on docs/introduction/developer-quickstart.md
> +Import and use the package in your components to interact with the Obscuro network.
can we be a bit more specific here?
What exactly do you have to do after installing the plugin?

2023-11-01 10:12 UTC, tudor-malene approved these changes
lgtm

2023-11-01 11:34 UTC, merged